export const IS_NAV_ADMIN_BODY_USER = 'IS_NAV_BODY_USER';
export const IS_NAV_ADMIN_BODY_PRODUCT = 'IS_NAV_BODY_PRODUCT';
export const IS_NAV_MENU_LEFT = 'IS_NAV_MENU_LEFT';
export const LOGIN_APP_ADMIN = 'LOGIN_APP_ADMIN';
export const IS_LOGIN_APP_ADMIN = 'IS_LOGIN_APP_ADMIN';
