export const IS_NAV_ADMIN_BODY_USER = 'IS_NAV_BODY_USER';
export const IS_NAV_ADMIN_BODY_PRODUCT = 'IS_NAV_BODY_PRODUCT';
export const IS_NAV_ADMIN_BODY_REVIEW = 'IS_NAV_ADMIN_BODY_REVIEW';
export const IS_NAV_ADMIN_BODY_OPTION= 'IS_NAV_ADMIN_BODY_OPTION';
export const IS_NAV_ADMIN_BODY_ORDER= 'IS_NAV_ADMIN_BODY_ORDER';

export const IS_NAV_ADMIN_OPTION_ORDER= 'IS_NAV_ADMIN_OPTION_ORDER';
export const IS_NAV_ADMIN_NEWS= 'IS_NAV_ADMIN_NEWS';
export const IS_NAV_ADMIN_COMMENTS= 'IS_NAV_ADMIN_COMMENTS';
export const IS_NAV_ADMIN_CATEGORY_PRODUCT= 'IS_NAV_ADMIN_CATEGORY_PRODUCT';


export const IS_NAV_MENU_LEFT = 'IS_NAV_MENU_LEFT';
export const LOGIN_APP_ADMIN = 'LOGIN_APP_ADMIN';
export const IS_LOGIN_APP_ADMIN = 'IS_LOGIN_APP_ADMIN';
export const STATUS_SUCCESS_POST_PRODUCT = 'STATUS_SUCCESS_POST_PRODUCT';

export const POST_DATA_PRODUCT_ADMIN = 'POST_DATA_PRODUCT_ADMIN';

export const POST_DATA_USER_ADMIN = 'POST_DATA_USER_ADMIN';

export const POST_DATA_OPTION_ADMIN = 'POST_DATA_OPTION_ADMIN';
export const GET_DATA_OPTION_ADMIN = 'GET_DATA_OPTION_ADMIN';
export const DELETE_DATA_OPTION_ADMIN = 'DELETE_DATA_OPTION_ADMIN';
export const PUT_DATA_OPTION_ADMIN = 'PUT_DATA_OPTION_ADMIN';
export const PUT_BODY_DATA_OPTION_ADMIN = 'PUT_BODY_DATA_OPTION_ADMIN';
export const DATA_OPTION_ADMIN = 'DATA_OPTION_ADMIN';

export const POST_DATA_REVIEW_ADMIN = 'POST_DATA_REVIEW_ADMIN';

export const POST_DATA_COMMENT_ADMIN = 'POST_DATA_COMMENT_ADMIN';


export const POST_CATEGORY_PRODUCT_ADMIN = 'POST_CATEGORY_PRODUCT_ADMIN';
export const PUT_CATEGORY_PRODUCT_ADMIN = 'POST_CATEGORY_PRODUCT_ADMIN';
export const DELETE_CATEGORY_PRODUCT_ADMIN = 'DELETE_CATEGORY_PRODUCT_ADMIN';
