export const IS_NAV_ADMIN_BODY_USER = 'IS_NAV_BODY_USER';
export const IS_NAV_ADMIN_BODY_PRODUCT = 'IS_NAV_BODY_PRODUCT';
export const IS_NAV_ADMIN_BODY_REVIEW = 'IS_NAV_ADMIN_BODY_REVIEW';
export const IS_NAV_ADMIN_BODY_OPTION = 'IS_NAV_ADMIN_BODY_OPTION';
export const IS_NAV_ADMIN_BODY_ORDER = 'IS_NAV_ADMIN_BODY_ORDER';

export const IS_NAV_ADMIN_OPTION_ORDER = 'IS_NAV_ADMIN_OPTION_ORDER';
export const IS_NAV_ADMIN_NEWS = 'IS_NAV_ADMIN_NEWS';
export const IS_NAV_ADMIN_COMMENTS = 'IS_NAV_ADMIN_COMMENTS';
export const IS_NAV_ADMIN_CATEGORY_PRODUCT = 'IS_NAV_ADMIN_CATEGORY_PRODUCT';


export const IS_NAV_MENU_LEFT = 'IS_NAV_MENU_LEFT';
export const LOGIN_APP_ADMIN = 'LOGIN_APP_ADMIN';
export const LOGIN_APP_USER = 'LOGIN_APP_USER';
export const SIGNUP_APP_USER = 'SIGNUP_APP_USER';

export const IS_LOGIN_APP_ADMIN = 'IS_LOGIN_APP_ADMIN';
export const STATUS_SUCCESS_POST_PRODUCT = 'STATUS_SUCCESS_POST_PRODUCT';
export const STATUS_POST_SIGNUP = 'STATUS_POST_SIGNUP';


export const POST_DATA_PRODUCT_ADMIN = 'POST_DATA_PRODUCT_ADMIN';
export const PUT_DATA_PRODUCT_ADMIN = 'PUT_DATA_PRODUCT_ADMIN';
export const FETCH_GET_DETAIL_PRODUCT = 'FETCH_GET_DETAIL_PRODUCT';
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_SUCCESS_USER = 'AUTH_SUCCESS_USER';
export const IS_AUTH_SUCCESS = 'IS_AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT';
export const AUTH_INITITATE_LOGOUT_USER = 'AUTH_INITITATE_LOGOUT_USER';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const POST_DATA_OPTION_ADMIN = 'POST_DATA_OPTION_ADMIN';
export const GET_DATA_OPTION_ADMIN = 'GET_DATA_OPTION_ADMIN';
export const DELETE_DATA_OPTION_ADMIN = 'DELETE_DATA_OPTION_ADMIN';
export const PUT_DATA_OPTION_ADMIN = 'PUT_DATA_OPTION_ADMIN';
export const DATA_OPTION_ADMIN = 'DATA_OPTION_ADMIN';

export const POST_DATA_REVIEW_ADMIN = 'POST_DATA_REVIEW_ADMIN';
export const DELETE_DATA_REVIEW_ADMIN = 'DELETE_DATA_REVIEW_ADMIN';
export const PUT_DATA_REVIEW_ADMIN = 'PUT_DATA_REVIEW_ADMIN';

export const POST_DATA_COMMENT_ADMIN = 'POST_DATA_COMMENT_ADMIN';


export const POST_CATEGORY_PRODUCT_ADMIN = 'POST_CATEGORY_PRODUCT_ADMIN';
export const PUT_CATEGORY_PRODUCT_ADMIN = 'POST_CATEGORY_PRODUCT_ADMIN';
export const DELETE_CATEGORY_PRODUCT_ADMIN = 'DELETE_CATEGORY_PRODUCT_ADMIN';


export const POST_USER_ADMIN = 'POST_USER_ADMIN';
export const PUT_USER_ADMIN = 'PUT_USER_ADMIN';
export const DELETE_USER_ADMIN = 'DELETE_USER_ADMIN';


export const POST_DATA_NEWS_ADMIN = 'POST_DATA_NEWS_ADMIN';
export const DELETE_DATA_NEWS_ADMIN = 'DELETE_DATA_NEWS_ADMIN';
export const PUT_DATA_NEWS_ADMIN = 'PUT_DATA_NEWS_ADMIN';